# -*- coding: utf-8 -*-
"""cp3 Prompt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Uw16igap-BuvlAfQ7jZYdShFAT7eEgO
"""

# A) Instala o descompactador zstd exigido pelo instalador do Ollama
!sudo apt-get update && sudo apt-get install -y zstd

# B) Instala as bibliotecas Python necessárias para o projeto
!pip install ollama chromadb ipywidgets

# C) Instala o executável do Ollama no Linux do Colab
!curl -fsSL https://ollama.com/install.sh | sh

# D) Inicializa o servidor local do Ollama em segundo plano
import subprocess
import time
try:
    subprocess.Popen(["ollama", "serve"])
    time.sleep(4) # Aguarda o servidor inicializar completamente
    print("✅ Servidor Ollama iniciado com sucesso em segundo plano!")
except FileNotFoundError:
    print("❌ Erro: Executável do Ollama não encontrado.")

# E) Faz o download do modelo Llama 3.2 (1 Billion)
!ollama pull llama3.2:1b

import ollama

perguntas_teste = [
    "Qual é o protocolo de comunicação padrão e a frequência de envio dos dados de telemetria?",
    "Como os inversores híbridos da GoodWe atuam junto com o ChargeOps na recarga de EVs?",
    "O que o sistema faz caso a estação de recarga perca a conexão com a internet local?",
    "Qual é a receita anual da Tesla com a venda de créditos de carbono nos Estados Unidos?",
    "O sistema usa inteligência artificial para prever o preço das ações da GoodWe na bolsa?",
]

print("=" * 60)
print("🧪 EXECUTANDO TESTES RAG — EV CHALLENGE 2026")
print("=" * 60)

for p in perguntas_teste:
    resultados = colecao.query(query_texts=[p], n_results=2)
    contexto = "\n".join(resultados["documents"][0])

    prompt = (
        "Diretrizes: Responda de forma estritamente técnica com base apenas no CONTEXTO fornecido. "
        "Se a resposta não puder ser deduzida do contexto ou se fugir do escopo (recarga de VEs, inversores GoodWe), "
        "responda obrigatoriamente e sem justificativas: 'Lamento, mas essa informação não consta na minha base de dados atual.'\n\n"
        f"CONTEXTO:\n{contexto}\n\n"
        f"PERGUNTA: {p}"
    )

    r = ollama.chat(model="llama3.2:1b", messages=[{"role": "user", "content": prompt}])
    print(f"\n👤 Pergunta: {p}")
    print(f"🤖 Resposta: {r['message']['content']}")
    print("─" * 60)

import ipywidgets as widgets
from IPython.display import display, HTML
import ollama

# 1. Inicialização do Histórico Limpo (Apenas com a instrução de Persona)
historico = [{
    "role": "system",
    "content": (
        "Você é um assistente técnico em EV ChargeOps e GoodWe. "
        "Sua única tarefa é responder à pergunta do usuário baseando-se no contexto fornecido. "
        "Seja extremamente direto, curto e use os dados numéricos do contexto. "
        "Não repita as instruções que recebeu."
    )
}]

# 2. Definição dos Componentes Visuais (Título personalizado com o seu Nome e RM)
titulo = widgets.HTML(
    "<h3 style='font-family:sans-serif; color:#007bff; margin-bottom: 5px;'>🔌 EV ChargeOps Bot — EV Challenge 2026</h3>"
    "<p style='font-family:sans-serif; color:#666; font-size:12px; margin-top: 0px; margin-bottom: 15px;'>"
    "<b>Desenvolvedor:</b> Pedro Soares de Souza | <b>RM:</b> 571285"
    "</p>"
)

area_chat = widgets.Output(layout=widgets.Layout(
    height="320px", overflow_y="auto", border="1px solid #ddd", padding="10px", margin="0 0 10px 0"
))

campo_texto = widgets.Text(
    placeholder="Digite sua dúvida sobre recarga e infraestrutura GoodWe...", layout=widgets.Layout(width="75%")
)

botao_enviar = widgets.Button(
    description="Enviar 📨", button_style="primary", layout=widgets.Layout(width="23%")
)

botao_limpar = widgets.Button(
    description="Limpar Histórico 🗑️", button_style="warning", layout=widgets.Layout(width="100%", margin="10px 0 0 0")
)

barra = widgets.HBox([campo_texto, botao_enviar])

# 3. Lógica do Pipeline RAG com separação rígida de System/User
def ao_enviar_com_rag(b):
    pergunta = campo_texto.value.strip()
    if not pergunta:
        return
    campo_texto.value = ""

    # Balão do Usuário (Direita - Azul)
    with area_chat:
        display(HTML(
            f'<div style="text-align:right;margin:6px 0">'
            f'<span style="background:#007bff;color:white;padding:7px 13px;'
            f'border-radius:18px 18px 4px 18px;display:inline-block;font-family:sans-serif">👤 {pergunta}</span></div>'
        ))

    # Executa a busca por similaridade semântica no ChromaDB
    try:
        resultados = colecao.query(query_texts=[pergunta], n_results=2)
        contexto = "\n".join(resultados["documents"][0])
    except Exception:
        contexto = "Erro ao acessar a base do ChromaDB."

    # Se a pergunta for totalmente fora do escopo, o próprio código bloqueia antes de mandar para o LLM
    palavras_chave = ["potência", "kw", "protocolo", "ocpp", "charging", "bess", "bateria", "status", "telemetria", "conexão", "solar", "inversor", "esg", "autenticação", "api", "carregador", "vaga"]
    forca_bloqueio = not any(palavra in pergunta.lower() for palavra in palavras_chave)

    if forca_bloqueio:
        resposta = "Lamento, mas essa informação não consta na minha base de dados atual."
    else:
        # Montamos a mensagem do usuário contendo o contexto e a pergunta de forma simples
        conteudo_usuario = (
            f"CONTEXTO DO PROJETO:\n{contexto}\n\n"
            f"PERGUNTA DO USUÁRIO: {pergunta}\n\n"
            "RESPONDA APENAS A PERGUNTA USANDO O CONTEXTO:"
        )

        try:
            # Enviamos a estrutura correta: System (Persona) + User (Dados + Pergunta)
            resposta_obj = ollama.chat(
                model="llama3.2:1b",
                messages=[
                    {"role": "system", "content": historico[0]["content"]},
                    {"role": "user", "content": conteudo_usuario}
                ]
            )
            resposta = resposta_obj["message"]["content"].strip()
        except Exception as e:
            resposta = f"Erro na comunicação com o Ollama: {str(e)}"

    # Atualiza o histórico para registro da sessão
    historico.append({"role": "user", "content": pergunta})
    historico.append({"role": "assistant", "content": resposta})

    # Balão do Assistente (Esquerda - Cinza)
    with area_chat:
        display(HTML(
            f'<div style="text-align:left;margin:6px 0">'
            f'<span style="background:#e9ecef;color:#212529;padding:7px 13px;'
            f'border-radius:18px 18px 18px 4px;display:inline-block;font-family:sans-serif">🤖 {resposta}</span></div>'
        ))

def ao_limpar_com_rag(b):
    area_chat.clear_output()
    with area_chat:
        display(HTML("<i style='color:#999;font-family:sans-serif'>Conversa reiniciada e memória limpa! ✨</i>"))

# 4. Vinculação dos Gatilhos de Eventos
botao_enviar.on_click(ao_enviar_com_rag)
campo_texto.on_submit(ao_enviar_com_rag)
botao_limpar.on_click(ao_limpar_com_rag)

# 5. Renderização Final
display(titulo, area_chat, barra, botao_limpar)